### ISSUE TITLE
compilation

### ISSUE THREAD

**Issue by szymet02** [ee3213/lol-leveling-bot-old#1]
When I compile this to execution file It shows up on second and then exits itself.

**Comment by ee3213** [comment]
I'm currently in the middle of a re-write of the entire code because the current implementation seems to only work on 50% of other machines.  Plus, the code is super messy.

I haven't worked on it much due to school, so I apologize that it isn't working.  I'll update the README

**Comment by lordcreations** [comment]
I hope you can finish it as soon as possible, I'm really excited to try it out!

> I'm currently in the middle of a re-write of the entire code because the current implementation seems to only work on 50% of other machines. Plus, the code is super messy.
> 
> I haven't worked on it much due to school, so I apologize that it isn't working. I'll update the README


I hope you can finish it as soon as possible, I'm really excited to try it out!
